### PR TITLE
Feat/dbc table filters

### PR DESCRIPTION
**Pull request by StevenHee**
TICKET: https://hee-tis.atlassian.net/browse/TIS21-3582

### CODE REVIEW

**Review by JosephKelly — COMMENTED** [review]
Looks like there's a bit of TypeScript advice from Github to address: `OnDestroy` interface.

We've agreed to follow conventional commit syntax.  It's a bit harder to see what has been done and why.

**Comment by StevenHee** [comment]
> Looks like there's a bit of TypeScript advice from Github to address: `OnDestroy` interface.
> 
> We've agreed to follow conventional commit syntax. It's a bit harder to see what has been done and why.

Can you share the advice from Github

**Comment by JosephKelly** [comment]
> > Looks like there's a bit of TypeScript advice from Github to address: `OnDestroy` interface.
> > We've agreed to follow conventional commit syntax. It's a bit harder to see what has been done and why.
> 
> Can you share the advice from Github

Just seen this comment.  It's on the `files`/diff page: https://github.com/Health-Education-England/tis-revalidation-v2/pull/969/files#diff-5ca6373781d4c54c2ed5e61c74c124eddb356693e5527479fb50c412c9a7a7beR61

`src/app/records/record-list-table-filters/record-list-table-filters.component.ts` implements the method ngOnDestroy() so I'm expecting the class should be defined as `export class RecordListTableFiltersComponent implements OnInit, OnDestroy`

**Review by JosephKelly — APPROVED** [review]
LGTM

**Pull request merged**
